name: Benchmarks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Benchmarks
        run: go test -benchmem -run=^$ -bench ^.*$ github.com/mlange-42/track/core
